### ISSUE TITLE
Priest Wand Spec

### ISSUE THREAD

**Issue by C00LED** [NeXan-Warcraft/NeXan#1]
1/5 - 15%
2/5 - 30%
3/5 - 15%
4/5 - 20%
5/5 - 25%

**Comment by Interweb5** [comment]
Solved, yet it is visually bugged, should be fixed in the next patch update.The damage scaling works starting at 5% to 25%.

**Comment by NeXan-Warcraft** [comment]
This issue has been fixed and will now scale from 5% to 25%. The visual edit will on the next patch update.
