### ISSUE TITLE
Roll the Bones - Quest

### ISSUE THREAD

**Issue by orakaine** [NeXan-Warcraft/NeXan#10]
The quest started me out with 1/8 [Dinosaur Bones] on the tracker.
Thus resulting in the quest counting itself completed once I only had 7 [Dinosaur Bones] in my inventory.
Unable to turn the quest in.. Even when the Quest Giver had a [?] above his head.
I was able to collect an 8th [Dinosaur Bone] and turn the quest in, although the tracker for it is bugged due to starting at 1/8.

**Comment by XxRenderxX** [comment]
This issue couldn't been replicated, it's possibly a client side glitch. Further investigations will be done.

**Comment by orakaine** [comment]
Some visual bug on my end then.
