### ISSUE TITLE
Impact Shot and Wicked Arrow Sold by Vendors

### ISSUE THREAD

**Issue by KingSothar** [NeXan-Warcraft/NeXan#13]
Impact Shot and Wicked Arrow (ammunition) was added during TBC. This item upsets balance greatly at level 60 as it has 5 more DPS than Thorium Shells/Thorium-threaded Arrow (the primary ammo in vanilla).

These ammunition existing cause engineering to be less valuable as well as engineers make Thorium Shells.

**Comment by XxRenderxX** [comment]
They have been removed.
