### ISSUE TITLE
Mount Cast Speed too Fast

### ISSUE THREAD

**Issue by KingSothar** [NeXan-Warcraft/NeXan#19]
Mounts were a 3 second cast in Vanilla and were changed to 1.5 in patch 3.2.

**Comment by XxRenderxX** [comment]
Quality of Life implementation. 👍

**Comment by KingSothar** [comment]
That's a ridiculous answer. The cast speed needs to be higher. It's a good way to punish mounts in PvP, which often are used as easy escapes from every situation. They never should have been lowered IMO. This is not a quality of life change it's a major balance change that needs to be addressed. Why should players be allowed to escape so quickly with mounts? Positioning is extremely important in PvP in this game.

**Comment by XxRenderxX** [comment]
This is being reconsidered, we will have a final answer soon to this.

**Comment by XxRenderxX** [comment]
Accepted, implemented in next patch update.
