### ISSUE TITLE
Stratholme Bugs

### ISSUE THREAD

**Issue by KingSothar** [NeXan-Warcraft/NeXan#22]
-Rammstein spawns on last dead mob instead of the door to ziggaurt.
-Encountering Rammstein does not close the gate.
-Zombies flood into room before Rammstein dies.
-Timmy the Cruel spawns on last dead mob instead of the entrance to human side.
-Timmy the Cruel respawns.
-Encountering Timmy the Cruel does not close gate.
-Encountering Baron does not close door when engaged.
-Encountering Grand Crusader Dathrohan does not close his door.

**Comment by lnterwebs** [comment]
All of the above has been fixed, and works correctly.
