### ISSUE TITLE
The Swarm Grows Should Require Egg Hunt

### ISSUE THREAD

**Issue by KingSothar** [NeXan-Warcraft/NeXan#25]
Description: Quest The Swarm Grows (ID: 1145) should require Egg Hunt (ID: 868) as completed to be available.

Current: The Swarm Grows can be accepted at any time.

Expected: Read Description.

Steps to reproduce the problem: Talk to Korran.

Screenshots (Recommended): //

Operating system (Optional) : Why is this on these tickets?

Addons/MPQs (Optional) List any other MPQs, addons, and any other customizations:

Comments (Optional):

**Comment by lnterwebs** [comment]
Fixed. Active on next server restart.

P.S: The OS is listed for technical issues/bugs etc. hence, why it's optional.
