### ISSUE TITLE
 [Magic Absorption]

### ISSUE THREAD

**Issue by C00LED** [NeXan-Warcraft/NeXan#26]
Description:  [Magic Absorption] increses resistances .5 per point (1 max) per level and causes all spells resisted to restore 1%(+1% per point) of total mana.

Current: 2/5 = 60 resistance + 2% restored.  3/5 = 59 resistance + 3% restored. (4/5 + 5/5) same resistance. 

Expected: 60 resistance at 2/5 onward

Screenshots (Recommended): https://imgur.com/a/0heOR

**Comment by lnterwebs** [comment]
Confirmed, images were a bit blurry but I found the issue.

**Comment by lnterwebs** [comment]
This has been hotfixed, server side, it will be visually fixed with the next MPQ update.
This should give 2 resistance each point
Source: (http://db.vanillagaming.org/?talent#o)
P - R
1 - 2
2 - 4
3 - 6
4 - 8
5 - 10
